//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.UDLImport.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UDM.UDLImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SystemFC_FB_List&gt;
        ///  &lt;SystemFunction Name=&quot;SFB0&quot; PLCMaker=&quot;Siemens&quot; Symbol=&quot;CTU&quot; Dexcription=&quot;CTU, IEC_TC&quot;&gt;
        ///    &lt;Label Name=&quot;IN0&quot; Address=&quot;0.0&quot; Usage=&quot;Input&quot; Datatype=&quot;Bool&quot; /&gt;
        ///    &lt;Label Name=&quot;IN1&quot; Address=&quot;0.1&quot; Usage=&quot;Input&quot; Datatype=&quot;Bool&quot; /&gt;
        ///    &lt;Label Name=&quot;IN2&quot; Address=&quot;2.0&quot; Usage=&quot;Input&quot; Datatype=&quot;Int&quot; /&gt;
        ///    &lt;Label Name=&quot;OUT3&quot; Address=&quot;4.0&quot; Usage=&quot;Output&quot; Datatype=&quot;Bool&quot; /&gt;
        ///    &lt;Label Name=&quot;OUT4&quot; Address=&quot;6.0&quot; Usage=&quot;Output&quot; Datatype=&quot;Int&quot; /&gt;
        ///  &lt;/SystemFunction&gt;
        ///  &lt;Sys[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemFuncAndFBList {
            get {
                return ResourceManager.GetString("SystemFuncAndFBList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;InstructionList&gt;
        ///  &lt;Instruction Name=&quot;XIC&quot;&gt;
        ///    &lt;Command Name=&quot;XIC&quot; Maker=&quot;AB&quot; SourceLabelNum=&quot;1&quot; CoilLabelNum=&quot;0&quot; /&gt;
        ///    &lt;Command Name=&quot;LD&quot; Maker=&quot;Mitsubishi&quot; SourceLabelNum=&quot;1&quot; CoilLabelNum=&quot;0&quot; /&gt;
        ///    &lt;Command Name=&quot;AND&quot; Maker=&quot;Mitsubishi&quot; SourceLabelNum=&quot;1&quot; CoilLabelNum=&quot;0&quot; /&gt;
        ///    &lt;Command Name=&quot;OR&quot; Maker=&quot;Mitsubishi&quot; SourceLabelNum=&quot;1&quot; CoilLabelNum=&quot;0&quot; /&gt;
        ///    &lt;Command Name=&quot;A&quot; Maker=&quot;Siemens&quot; SourceLabelNum=&quot;1&quot; CoilLabelNum=&quot;0&quot; /&gt;
        ///    &lt;Command Name=&quot;O&quot; Maker=&quot;Siemens&quot; Sour[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TotalInstruListNew {
            get {
                return ResourceManager.GetString("TotalInstruListNew", resourceCulture);
            }
        }
    }
}
