-- company
INSERT INTO COMPANY_TB (`COMPANY_NAME`, `REGISTRATION_NUMBER`, `KIND`, `STATUS`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES ('AA101직판점', 'AA102', 'DEALER', 'REGISTERED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `COMPANY_TB` (`COMPANY_NAME`, `REGISTRATION_NUMBER`, `KIND`, `STATUS`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES ('AA201사용점', 'AA202', 'CONSUMER', 'REGISTERED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO `COMPANY_TB` (`COMPANY_NAME`, `REGISTRATION_NUMBER`, `KIND`, `STATUS`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES ('AA301직판점', 'AA302', 'CONSUMER', 'DISABLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
  
-- user
INSERT INTO USER_TB (`USERNAME`, `PASSWORD`, `ENABLED`, `POSITION`, `STATUS`, `FK_COMPANY_ID`)
  VALUES ('test', '$2a$10$ptMDU9t4/oZe8YC2x3kCkOcQvM6.8u9paBTSxzzUe9a7m8/suWQPm', 1, 'EMPLOYEE', 'REGISTERED', 1);
INSERT INTO USER_TB (`USERNAME`, `PASSWORD`, `ENABLED`, `POSITION`, `STATUS`, `FK_COMPANY_ID`)
  VALUES ('martin', '$2a$10$ACRP9z0Ya//Nbym3oQj9Keq4NNXwoq.oyCnUlx1819RvlzLcqDTJq/uExeP1TMa6wG21zwll3Yp9DUC', 1, 'EMPLOYEE', 'REGISTERED', 1);
  
-- role
INSERT INTO ROLE_TB (`ROLENAME`, `FK_USER_ID`)
    VALUES ('ROLE_ADMIN', 1);
INSERT INTO ROLE_TB (`ROLENAME`, `FK_USER_ID`)
    VALUES ('ROLE_USER', 2);
    
-- compressor
INSERT INTO COMP_DATA_TB (
    `ID`, `BARCODE`, `MODEL_NAME`, `PRODUCT_NUMBER`, `AFTER_SERVICE_PERIOD`, `USING_STATUS`,
    `FK_COMPANY_ID_DEALER`, `FK_COMPANY_ID_CONSUMER`, `PUBLISH_TIME`, `START_USING_TIME`,
    `FK_USER_ID_CREATION`, `FK_USER_ID_MODIFICATION`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES (
    1, 'AA101', 'AA102', 'AA103', 'FIRST_YEAR', 'USING',
    1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
    2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  );
INSERT INTO COMP_DATA_TB (
    `ID`, `BARCODE`, `MODEL_NAME`, `PRODUCT_NUMBER`, `AFTER_SERVICE_PERIOD`, `USING_STATUS`,
    `FK_COMPANY_ID_DEALER`, `FK_COMPANY_ID_CONSUMER`, `PUBLISH_TIME`, `START_USING_TIME`,
    `FK_USER_ID_CREATION`, `FK_USER_ID_MODIFICATION`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES (
    2, 'BB101', 'BB102', 'BB103', 'FIRST_YEAR', 'USING',
    1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
    2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  );
INSERT INTO COMP_DATA_TB (
    `ID`, `BARCODE`, `MODEL_NAME`, `PRODUCT_NUMBER`, `AFTER_SERVICE_PERIOD`, `USING_STATUS`,
    `FK_COMPANY_ID_DEALER`, `FK_COMPANY_ID_CONSUMER`, `PUBLISH_TIME`, `START_USING_TIME`,
    `FK_USER_ID_CREATION`, `FK_USER_ID_MODIFICATION`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES (
    3, 'CC101', 'CC102', 'CC103', 'FIRST_YEAR', 'USING',
    1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
    2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  );
INSERT INTO COMP_DATA_TB (
    `ID`, `BARCODE`, `MODEL_NAME`, `PRODUCT_NUMBER`, `AFTER_SERVICE_PERIOD`, `USING_STATUS`,
    `FK_COMPANY_ID_DEALER`, `FK_COMPANY_ID_CONSUMER`, `PUBLISH_TIME`, `START_USING_TIME`,
    `FK_USER_ID_CREATION`, `FK_USER_ID_MODIFICATION`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES (
    4, 'DD101', 'DD102', 'DD103', 'FIRST_YEAR', 'USING',
    1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
    2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  );
INSERT INTO COMP_DATA_TB (
    `ID`, `BARCODE`, `MODEL_NAME`, `PRODUCT_NUMBER`, `AFTER_SERVICE_PERIOD`, `USING_STATUS`,
    `FK_COMPANY_ID_DEALER`, `FK_COMPANY_ID_CONSUMER`, `PUBLISH_TIME`, `START_USING_TIME`,
    `FK_USER_ID_CREATION`, `FK_USER_ID_MODIFICATION`, `CREATION_TIME`, `MODIFICATION_TIME`)
  VALUES (
    5, 'EE101', 'EE102', 'EE103', 'FIRST_YEAR', 'USING',
    1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
    2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  );

-- driving condition
INSERT INTO COMP_00_TB (`ID`, `FK_PRODUCT_NUMBER`, `00_00`, `00_01`, `00_02`, `00_03`, `00_04`, `00_05`, `SAVETIME`)
  VALUES (0, 'BB103', '68.0', '6.0', '25.0', '12.0', '69.0', '10.0', CURRENT_TIMESTAMP);
INSERT INTO COMP_00_TB (`ID`, `FK_PRODUCT_NUMBER`, `00_00`, `00_01`, `00_02`, `00_03`, `00_04`, `00_05`, `SAVETIME`)
  VALUES (1, 'CC103', '78.0', '7.0', '55.0', '22.0', '79.0', '30.0', CURRENT_TIMESTAMP);

-- warning range setting
INSERT INTO COMP_06_TB (`ID`, `FK_PRODUCT_NUMBER`, `06_00`, `06_01`, `06_02`, `06_03`, `06_04`, `06_05`, `SAVETIME`)
  VALUES (0, 'BB103', '80.0', '20.0', '85.0', '25.0', '15.0', '45.0', CURRENT_TIMESTAMP);
INSERT INTO COMP_06_TB (`ID`, `FK_PRODUCT_NUMBER`, `06_00`, `06_01`, `06_02`, `06_03`, `06_04`, `06_05`, `SAVETIME`)
  VALUES (1, 'CC103', '70.0', '20.0', '85.0', '25.0', '15.0', '45.0', CURRENT_TIMESTAMP);