DROP TABLE `COMPANY_TB`;
CREATE TABLE `COMPANY_TB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(255) DEFAULT NULL,
  `REGISTRATION_NUMBER` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `KIND` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime DEFAULT NULL,
  `MODIFICATION_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE `USER_TB`;
CREATE TABLE `USER_TB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ENABLED` int(1) DEFAULT 1,
  `POSITION` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime DEFAULT NULL,
  `MODIFICATION_TIME` datetime DEFAULT NULL,
  `FK_COMPANY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
  
DROP TABLE `ROLE_TB`;
CREATE TABLE `ROLE_TB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLENAME` varchar(255) DEFAULT NULL,
  `FK_USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `COMP_DATA_TB` CHANGE `STATUS` USING_STATUS varchar(255) DEFAULT NULL;
